### ISSUE TITLE
硬编码问题

### ISSUE THREAD

**Issue by defaul0t** [roncoo/roncoo-education#24]
1.ｘ使用的ｘｌ－ｊｏｂ组件存在默认的ｔｏｋｅｎ值，将会导致命令执行的风险

![1692346016813](https://github.com/roncoo/roncoo-education/assets/49946499/9e974a79-24ef-45c5-9065-79568a15ea43)

找到ｘｘｌ的接口端口，默认是9998

POST /run HTTP/1.1
Host: 127.0.0.1:9998
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Connection: close
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
XXL-JOB-ACCESS-TOKEN: education-job
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Content-Type: application/x-www-form-urlencoded
Content-Length: 0

验证这个请求是否成功

**Comment by fengyws** [comment]
感谢反馈，已经处理
